import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'ja' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  ja: {
    'nav.home': 'ホーム',
    'nav.services': '事業内容',
    'nav.company': '企業情報',
    'nav.contact': 'お問い合わせ',
    'hero.title': '長岡から、子どもたちの「遊ぶ場所」をつくる。',
    'hero.subtitle': '玩具・ホビーの卸売（B2B）を中心に、小売・買取まで一貫して手がけています。',
    'hero.cta': '事業内容を見る',
    'services.title': '事業紹介',
    'services.subtitle': '小売店様向けの卸売（B2B）を中心に、小売・買取・マーケティング支援まで、玩具の流通を一貫して担っています。',
    'services.b2c.title': '物販事業 (B2C)',
    'services.b2c.desc': 'Amazon、楽天市場、Yahoo!ショッピングなど、主要ECモールを通じて、お客様に直接商品をお届けします。安全性とスピードを重視し、快適なショッピング体験を提供します。',
    'services.b2b.title': '卸売事業 (B2B)',
    'services.b2b.desc': '玩具店・ホビーショップ・小売業者様へ、玩具およびホビー商材を安定的にお届けします。少量からのお取引にも対応し、必要な数を、必要なときに。支払条件・納期のご相談も承ります。',
    'services.b2b.list1': 'トレーディングカード・ホビー商品',
    'services.b2b.list2': '知育玩具',
    'services.b2b.list3': '日用品',
    'services.sns.title': 'SNSマーケティング支援',
    'services.sns.desc': '独自に培ったSNS販売戦略に基づく、実践的なコンサルティングをご提供します。理論だけでなく、私たちが実際に成果を出した「売れる」ためのノウハウを共有します。',
    'services.sns.expertise.title': '私たちの強み',
    'services.sns.expertise.desc': 'コンテンツ制作からコミュニティ運営まで、Instagram、X (Twitter)、TikTokなどのプラットフォームで顧客とエンゲージメントを築くための詳細なガイドを行います。',
    'services.buying.title': '買取事業',
    'services.buying.desc': '古物商許可に基づき、対面・非対面（宅配）での買取を行っております。大切なお品物を丁寧に査定いたします。',
    'services.buying.in_person.title': '対面買取',
    'services.buying.in_person.desc': '店舗に直接お持ち込みいただき、その場で査定・買取いたします。',
    'services.buying.mail_in.title': '宅配買取',
    'services.buying.mail_in.desc': '全国どこからでも郵送で買取可能です。簡単・便利にご利用いただけます。',
    'services.buying.commitment': '「にこにこ買取」として、X (Twitter) を中心に活動中。業界最高価格での買取を目指しております。',
    'store.badge': '計画中',
    'store.title': '長岡市に、玩具店舗を計画しています',
    'store.lead': '長岡には、子どもが気軽に遊べる場所がそれほど多くありません。夏は暑く、冬は雪に閉ざされます。それなら、天気に左右されずに立ち寄れる場所をつくればいい。私たちはそう考えました。',
    'store.body': '玩具を売るだけの店ではなく、子どもたちが実際に手に取り、遊び、過ごせる場所にしたいと考えています。地域の親子が「今日はどこへ行こう」と迷ったときに、思い出してもらえる場所を目指します。',
    'store.note': '※ 開設に向けて準備を進めている段階です。場所・時期が決まり次第、本ページでお知らせします。',
    'trust.title': '会社としての基本情報',
    'trust.desc': 'お取引にあたってご確認いただける、公的な登録情報です。',
    'trust.corp': '法人番号',
    'trust.license': '古物商許可',
    'trust.invoice': '適格請求書発行事業者',
    'trust.est': '設立',
    'company.title': '企業情報',
    'company.profile_title': '会社概要',
    'company.name': '会社名',
    'company.name_value': '株式会社AiGIVE',
    'company.rep': '代表者',
    'company.rep_value': '内藤 夏樹',
    'company.address': '所在地',
    'company.address_value': '〒940-0062 新潟県長岡市大手通2-2-6',
    'company.est': '設立',
    'company.est_value': '2024年6月',
    'company.capital': '資本金',
    'company.capital_value': '500万円',
    'company.business': '事業概要',
    'company.business_value': '玩具・日用品の卸売・販売、マーケティング支援',
    'company.license': '古物商許可番号',
    'company.license_value': '第461350000709号',
    'company.license_auth': '公安委員会',
    'company.license_auth_value': '新潟県公安委員会',
    'company.license_date': '許可年月日',
    'company.license_date_value': '令和6年（2024年）7月25日',
    'company.corporate_number': '法人番号',
    'company.corporate_number_value': '5110001038461',
    'company.invoice_number': '適格請求書発行事業者',
    'company.invoice_number_value': 'T5110001038461',
    'company.email': 'メールアドレス',
    'company.email_value': 'info@aigive.jp',
    'contact.title': 'お問い合わせ',
    'contact.subtitle': 'ご質問やご相談がございましたら、お気軽にお問い合わせください。',
    'contact.company': '御社名 / 屋号',
    'contact.ph.company': '例：株式会社○○',
    'contact.ph.name': '例：山田 太郎',
    'contact.ph.type': '選択してください',
    'contact.ph.message': 'お問い合わせ内容をご記入ください。',
    'contact.sending': '送信中…',
    'contact.thanks.title': '送信しました',
    'contact.back': 'フォームに戻る',
    'contact.name': 'お名前',
    'contact.email': 'メールアドレス',
    'contact.type': 'お問い合わせ種別',
    'contact.type.b2b': 'B2B取引について',
    'contact.type.consulting': 'コンサルティング依頼',
    'contact.type.buying': '買取について',
    'contact.type.other': 'その他',
    'contact.message': 'お問い合わせ内容',
    'contact.submit': '送信する',
    'contact.thanks.body': 'お問い合わせありがとうございます。内容を確認次第、担当者よりご連絡させていただきます。',
    'footer.privacy': 'プライバシーポリシー',
    'footer.copyright': '© 2024 AiGIVE CO.,LTD. All Rights Reserved.',
    'privacy.title': 'プライバシーポリシー',
    'privacy.intro': '株式会社AiGIVE（以下「当社」）は、個人情報の保護に関する法律その他の関係法令を遵守し、お客様の個人情報を適切に取り扱います。本ポリシーは、当社が取得する個人情報の取扱方針を定めるものです。',
    'privacy.updated': '制定日: 2026年8月16日',
    'privacy.section1.title': '1. 事業者の情報',
    'privacy.section1.content': '事業者名: 株式会社AiGIVE ／ 代表者: 内藤 夏樹 ／ 所在地: 〒940-0062 新潟県長岡市大手通2-2-6 ／ 法人番号: 5110001038461 ／ 個人情報保護管理者: 代表取締役',
    'privacy.section2.title': '2. 取得する個人情報',
    'privacy.section2.content': '当社は、以下の情報を取得することがあります。',
    'privacy.section2.list1': 'お問い合わせフォームでご入力いただく情報（氏名、メールアドレス、会社名、お問い合わせ内容）',
    'privacy.section2.list2': '取引に必要な情報（住所、電話番号、振込先口座、本人確認書類の記載事項）',
    'privacy.section2.list3': '古物営業法に基づき記録が義務づけられた情報（買取時の氏名、住所、職業、年齢、確認方法）',
    'privacy.section2.list4': 'ウェブサイトの利用情報（アクセス日時、閲覧ページ、IPアドレス、Cookie等の識別子）',
    'privacy.section3.title': '3. 利用目的',
    'privacy.section3.content': '取得した個人情報は、次の目的の範囲内で利用します。',
    'privacy.section3.list1': 'お問い合わせへの回答、ご連絡',
    'privacy.section3.list2': '商品の販売・卸売・買取に伴う契約の履行（受注、発送、代金の支払・受領）',
    'privacy.section3.list3': '古物営業法に基づく本人確認および古物台帳の作成・保存',
    'privacy.section3.list4': '法令に基づく書類の作成・保存（会計帳簿等）',
    'privacy.section3.list5': '当社サービスのご案内、およびサービスの改善',
    'privacy.section4.title': '4. 第三者への提供',
    'privacy.section4.content': '当社は、次のいずれかに該当する場合を除き、あらかじめご本人の同意を得ることなく個人情報を第三者に提供しません。法令に基づく場合／人の生命、身体または財産の保護に必要で本人の同意を得ることが困難な場合／国の機関等への協力が必要な場合。なお、古物営業法に基づく警察官等からの求めには、法令の定めるところにより応じることがあります。',
    'privacy.section5.title': '5. 業務委託先への提供',
    'privacy.section5.content': '当社は、配送、決済、システム運用等の業務を外部に委託することがあり、その範囲で必要な個人情報を委託先に提供します。委託先に対しては、契約等により適切な監督を行います。主な委託先の類型は、配送事業者、決済代行事業者、クラウドサービス事業者です。',
    'privacy.section6.title': '6. 国外への移転',
    'privacy.section6.content': '当社は海外事業者が提供するクラウドサービスを利用しているため、個人情報が国外に移転される場合があります。移転先の国の制度および講じられている保護措置については、下記の窓口へお問い合わせください。',
    'privacy.section7.title': '7. Cookie・アクセス解析',
    'privacy.section7.content': '当社ウェブサイトは、利用状況の把握のためCookieおよびアクセス解析ツールを利用することがあります。これらは個人を直接特定するものではありません。ブラウザの設定によりCookieを無効にできますが、一部機能がご利用いただけない場合があります。',
    'privacy.section8.title': '8. 安全管理措置',
    'privacy.section8.content': '当社は、個人情報の漏えい、滅失または毀損の防止その他の安全管理のために、取扱者の限定、アクセス権限の管理、通信の暗号化、保存データへのアクセス記録の取得等、必要かつ適切な措置を講じます。',
    'privacy.section9.title': '9. 保有個人データの開示・訂正・利用停止',
    'privacy.section9.content': 'ご本人からの求めにより、保有個人データの利用目的の通知、開示、内容の訂正・追加・削除、利用の停止・消去、第三者提供の停止に応じます。ご本人であることを確認のうえ、法令の定めに従い、合理的な期間内に回答します。手続費用は原則として無料です。',
    'privacy.section10.title': '10. 保存期間',
    'privacy.section10.content': '個人情報は利用目的の達成に必要な期間保管し、その後は遅滞なく消去します。ただし、古物営業法、会社法、法人税法その他の法令で保存期間が定められているものは、その期間保存します。',
    'privacy.section11.title': '11. 本ポリシーの変更',
    'privacy.section11.content': '当社は、法令の改正または事業内容の変更に応じて本ポリシーを改定することがあります。重要な変更を行う場合は、本ウェブサイトに掲載してお知らせします。',
    'privacy.section12.title': '12. お問い合わせ窓口',
    'privacy.section12.content': '個人情報の取扱いに関するお問い合わせ・開示等のご請求は、下記までお願いいたします。株式会社AiGIVE 個人情報お問い合わせ窓口 ／ 〒940-0062 新潟県長岡市大手通2-2-6 ／ info@aigive.jp',
    'common.learn_more': '詳細を見る',
    'common.contact_us': 'お問い合わせ',
  },
  en: {
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.company': 'Company',
    'nav.contact': 'Contact',
    'hero.title': 'Creating a place for children to play, from Nagaoka.',
    'hero.subtitle': 'Wholesale (B2B) is our core business, backed by retail and buying operations.',
    'hero.cta': 'View Services',
    'services.title': 'Our Services',
    'services.subtitle': 'Retail, Wholesale, Marketing, and Buying. We provide comprehensive solutions to deliver joy and value to our customers.',
    'services.b2c.title': 'Retail (B2C)',
    'services.b2c.desc': 'We deliver products directly to customers through major EC malls such as Amazon, Rakuten, and Yahoo! Shopping. We prioritize safety and speed to ensure a delightful shopping experience.',
    'services.b2b.title': 'Wholesale (B2B)',
    'services.b2b.desc': 'We propose various products to domestic trading card shops, toy stores, and retailers. Leveraging our unique network, we provide a stable supply of popular and rare items.',
    'services.b2b.list1': 'Trading Cards & Hobby Goods',
    'services.b2b.list2': 'Educational Toys',
    'services.b2b.list3': 'Daily Necessities',
    'services.sns.title': 'SNS Marketing Consulting',
    'services.sns.desc': 'We provide practical consulting based on our unique SNS sales strategies. We share not just theory, but the know-how to "sell" that has actually produced results for us.',
    'services.sns.expertise.title': 'Our Expertise',
    'services.sns.expertise.desc': 'From content creation to community management, we guide you through the nuances of engaging customers on platforms like Instagram, X (Twitter), and TikTok.',
    'services.buying.title': 'Buying Service',
    'services.buying.desc': 'Based on our antique dealer license, we offer both in-person and non-face-to-face (mail-in) buying services. We carefully appraise your valuable items.',
    'services.buying.in_person.title': 'In-Person',
    'services.buying.in_person.desc': 'Bring your items directly to our shop for immediate appraisal.',
    'services.buying.mail_in.title': 'Mail-In',
    'services.buying.mail_in.desc': 'Send your items from anywhere in Japan. Easy and convenient.',
    'services.buying.commitment': 'Operating as "Niko Niko Kaitori", primarily on X (Twitter). We aim to offer the highest purchase prices in the industry.',
    'store.badge': 'In planning',
    'store.title': 'We are planning a toy store in Nagaoka',
    'store.lead': 'Nagaoka has few places where children can drop in and play. Summers are hot and winters are buried in snow. So we decided to build a place you can visit whatever the weather.',
    'store.body': 'Not just a shop that sells toys, but a place where children can pick things up, play, and spend time. Somewhere local families remember when they wonder where to go today.',
    'store.note': '* We are currently preparing to open. The location and opening date will be announced on this page once decided.',
    'trust.title': 'Company registration details',
    'trust.desc': 'Public registration information you can verify before doing business with us.',
    'trust.corp': 'Corporate Number',
    'trust.license': 'Antique Dealer License',
    'trust.invoice': 'Qualified Invoice Issuer',
    'trust.est': 'Established',
    'company.title': 'Company Info',
    'company.profile_title': 'Corporate Profile',
    'company.name': 'Company Name',
    'company.name_value': 'AiGIVE CO.,LTD.',
    'company.rep': 'Representative',
    'company.rep_value': 'Natsuki Naito',
    'company.address': 'Address',
    'company.address_value': '2-2-6 Otedori, Nagaoka City, Niigata Pref. 940-0062',
    'company.est': 'Established',
    'company.est_value': 'June 2024',
    'company.capital': 'Capital',
    'company.capital_value': '5 Million JPY',
    'company.business': 'Business Overview',
    'company.business_value': 'Wholesale/Retail of Toys & Daily Goods, Marketing Support',
    'company.license': 'Antique Dealer License No.',
    'company.license_value': 'No. 461350000709',
    'company.license_auth': 'Public Safety Commission',
    'company.license_auth_value': 'Niigata Prefectural Public Safety Commission',
    'company.license_date': 'Date of Permit',
    'company.license_date_value': 'July 25, 2024',
    'company.corporate_number': 'Corporate Number',
    'company.corporate_number_value': '5110001038461',
    'company.invoice_number': 'Invoice Registration Number',
    'company.invoice_number_value': 'T5110001038461',
    'company.email': 'Email',
    'company.email_value': 'info@aigive.jp',
    'contact.title': 'Contact Us',
    'contact.subtitle': 'We\'d love to hear from you. Please fill out the form below.',
    'contact.company': 'Company name',
    'contact.ph.company': 'e.g. ABC Co., Ltd.',
    'contact.ph.name': 'e.g. Taro Yamada',
    'contact.ph.type': 'Please choose',
    'contact.ph.message': 'Please tell us what you need.',
    'contact.sending': 'Sending…',
    'contact.thanks.title': 'Thank You!',
    'contact.back': 'Back to the form',
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.type': 'Inquiry Type',
    'contact.type.b2b': 'B2B Transaction',
    'contact.type.consulting': 'Consulting Request',
    'contact.type.buying': 'Buying Service',
    'contact.type.other': 'Other',
    'contact.message': 'Message',
    'contact.submit': 'Send',
    'contact.thanks.body': 'Thank you for getting in touch. We will review your message and reply shortly.',
    'footer.privacy': 'Privacy Policy',
    'footer.copyright': '© 2024 AiGIVE CO.,LTD. All Rights Reserved.',
    'privacy.title': 'Privacy Policy',
    'privacy.intro': 'AiGIVE CO., LTD. ("we", "us") complies with the Act on the Protection of Personal Information and related laws of Japan, and handles your personal information appropriately. This policy sets out how we handle the personal information we obtain.',
    'privacy.updated': 'Established: 16 August 2026',
    'privacy.section1.title': '1. Business Operator',
    'privacy.section1.content': 'Name: AiGIVE CO., LTD. / Representative: Natsuki Naito / Address: 2-2-6 Otedori, Nagaoka, Niigata 940-0062, Japan / Corporate Number: 5110001038461 / Personal Information Manager: Representative Director',
    'privacy.section2.title': '2. Information We Collect',
    'privacy.section2.content': 'We may collect the following information.',
    'privacy.section2.list1': 'Information you enter in our inquiry form (name, email address, company name, message)',
    'privacy.section2.list2': 'Information required for transactions (address, telephone number, bank account details, identity document details)',
    'privacy.section2.list3': 'Information we are required to record under the Secondhand Articles Dealer Act (name, address, occupation, age and verification method at the time of purchase)',
    'privacy.section2.list4': 'Website usage data (access time, pages viewed, IP address, cookies and similar identifiers)',
    'privacy.section3.title': '3. Purposes of Use',
    'privacy.section3.content': 'We use personal information within the scope of the following purposes.',
    'privacy.section3.list1': 'Responding to and communicating about inquiries',
    'privacy.section3.list2': 'Performing contracts for retail, wholesale and purchase (orders, shipping, payment)',
    'privacy.section3.list3': 'Identity verification and maintaining the secondhand dealer ledger required by law',
    'privacy.section3.list4': 'Preparing and retaining records required by law (accounting books and others)',
    'privacy.section3.list5': 'Informing you about our services and improving them',
    'privacy.section4.title': '4. Provision to Third Parties',
    'privacy.section4.content': 'We do not provide personal information to third parties without your prior consent, except where required by law; where necessary to protect life, body or property and consent is difficult to obtain; or where cooperation with a public authority is required. We may respond to requests from the police under the Secondhand Articles Dealer Act as required by law.',
    'privacy.section5.title': '5. Outsourcing',
    'privacy.section5.content': 'We may outsource delivery, payment processing and system operations, and provide the necessary personal information to those contractors. We supervise contractors appropriately under contract. Typical categories are delivery companies, payment processors and cloud service providers.',
    'privacy.section6.title': '6. Cross-border Transfer',
    'privacy.section6.content': 'Because we use cloud services operated outside Japan, personal information may be transferred outside Japan. For information on the systems of the destination countries and the protective measures taken, please contact us at the address below.',
    'privacy.section7.title': '7. Cookies and Analytics',
    'privacy.section7.content': 'Our website may use cookies and analytics tools to understand usage. These do not directly identify individuals. You may disable cookies in your browser, although some features may then be unavailable.',
    'privacy.section8.title': '8. Security Measures',
    'privacy.section8.content': 'We take necessary and appropriate measures to prevent leakage, loss or damage of personal information, including limiting who handles it, managing access rights, encrypting communications and logging access to stored data.',
    'privacy.section9.title': '9. Disclosure, Correction and Suspension of Use',
    'privacy.section9.content': 'On request, we will notify you of the purpose of use, disclose, correct, add to, delete, suspend the use of, erase, or stop third-party provision of retained personal data. After verifying your identity, we will respond within a reasonable period as required by law. There is generally no charge.',
    'privacy.section10.title': '10. Retention Period',
    'privacy.section10.content': 'We retain personal information for as long as necessary to achieve the purpose of use and delete it promptly thereafter. Where a retention period is prescribed by law (Secondhand Articles Dealer Act, Companies Act, Corporation Tax Act and others), we retain it for that period.',
    'privacy.section11.title': '11. Changes to This Policy',
    'privacy.section11.content': 'We may revise this policy in response to changes in law or in our business. We will announce material changes on this website.',
    'privacy.section12.title': '12. Contact',
    'privacy.section12.content': 'For inquiries about the handling of personal information or to make a request for disclosure, please contact: AiGIVE CO., LTD., Personal Information Desk / 2-2-6 Otedori, Nagaoka, Niigata 940-0062, Japan / info@aigive.jp',
    'common.learn_more': 'Learn More',
    'common.contact_us': 'Contact Us',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('ja');

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['ja']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
